spring:
  application:
    name: kafka-demo-2

  kafka:
    consumer:
      # ??a ch? Kafka broker (c� th? l� 1 ho?c nhi?u, c�ch nhau b?ng d?u ph?y)
      bootstrap-servers: localhost:9092

      # M?i consumer ph?i thu?c 1 group. Kafka d�ng group-id ?? chia message.
      group-id: myGroup

      # N?u ch?a c� offset (v?a t?o m?i), ??c message t? ?�u?
      # earliest: ??c t? ??u topic
      # latest: ch? ??c c�c message m?i
      auto-offset-reset: earliest

      # Class d�ng ?? gi?i m� key t? byte -> String
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      # Class d�ng ?? gi?i m� value t? byte -> String
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      # C?u h�nh b? sung cho JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

    # C?u h�nh cho producer (g?i message l�n Kafka)
    producer:
      bootstrap-servers: localhost:9092

      # Class d�ng ?? m� h�a key t? String -> byte
      key-serializer: org.apache.kafka.common.serialization.StringSerializer

      # Class d�ng ?? m� h�a value t? String -> byte
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer