server:
  port: 8082

spring:
  application:
    name: quiz-service

  datasource:
    url: jdbc:mysql://localhost:3306/quiz-service
    username: root
    password: Dp17103919@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # create, create-drop, update, validate
    show-sql: true       # log c�u SQL
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    hostname: localhost

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true